//! CI-only validation for the real, freshly built standalone v2 plugin packages.
//!
//! The normal root workspace does not build plugin Components. The blocking
//! plugin-components job supplies both package paths after building and
//! packaging them, then explicitly runs this ignored test.

use std::path::{Path, PathBuf};

use bbcom_plugin_contracts::generated_v2::Capability;
use bbcom_plugin_repository::PluginInstaller;

const COUNTER_PACKAGE_ENV: &str = "BBCOM_COUNTER_V2_PACKAGE";
const MCUMGR_PACKAGE_ENV: &str = "BBCOM_MCUMGR_V2_PACKAGE";

fn required_package(name: &str) -> PathBuf {
    let configured = std::env::var_os(name)
        .map(PathBuf::from)
        .unwrap_or_else(|| panic!("{name} must point to a generated package directory"));
    if configured.is_absolute() {
        configured
    } else {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .join(configured)
    }
}

fn stage_v2(
    installer: &PluginInstaller,
    package: &Path,
    expected_id: &str,
    expected_capabilities: &[Capability],
) {
    let prepared = installer
        .prepare_local_install(package)
        .unwrap_or_else(|error| panic!("{} must be installable: {error}", package.display()));
    assert_eq!(prepared.plugin_id(), expected_id);
    assert_eq!(
        prepared.requested_capabilities().len(),
        expected_capabilities.len()
    );
    for capability in expected_capabilities {
        assert!(prepared.requested_capabilities().contains(capability));
    }

    let active = installer
        .commit_prepared(&prepared)
        .expect("the validated package must commit");
    assert_eq!(active.plugin_id, expected_id);
}

#[test]
#[ignore = "requires release Components generated by the plugin-components CI job"]
fn generated_counter_and_mcumgr_packages_install_through_production_pipeline() {
    let root = tempfile::tempdir().expect("installer root");
    let installer = PluginInstaller::new(root.path().join("packages"), root.path().join("data"))
        .expect("installer");

    stage_v2(
        &installer,
        &required_package(COUNTER_PACKAGE_ENV),
        "dev.bbcom.counter-v2",
        &[
            Capability::UiWorkspace,
            Capability::SerialSessionsManage,
            Capability::SerialIo,
            Capability::SessionCommandsReadWrite,
            Capability::ProjectStateReadWrite,
        ],
    );
    stage_v2(
        &installer,
        &required_package(MCUMGR_PACKAGE_ENV),
        "dev.bbcom.mcumgr-client",
        &[
            Capability::UiWorkspace,
            Capability::UiDetachedWindow,
            Capability::SerialPortsRead,
            Capability::SerialSessionsManage,
            Capability::SerialIo,
            Capability::SerialControlLines,
            Capability::SessionCaptureRead,
            Capability::SessionCommandsReadWrite,
            Capability::FileOpenRead,
            Capability::FileSaveWrite,
            Capability::ProjectStateReadWrite,
        ],
    );

    let active = installer.active_installations();
    assert_eq!(active.len(), 2);
    assert_eq!(active[0].plugin_id, "dev.bbcom.counter-v2");
    assert_eq!(active[1].plugin_id, "dev.bbcom.mcumgr-client");
}
