export {
  AUTO_LOG_APPEND_TIMEOUT_MS,
  AUTO_LOG_DEBOUNCE_MS,
  AUTO_LOG_DRAIN_TIMEOUT_MS,
  AUTO_LOG_FAILURE_EVENT,
  AUTO_LOG_IMMEDIATE_FLUSH_BYTES,
  AUTO_LOG_MAX_BATCH_BYTES,
  AUTO_LOG_MAX_BATCH_FRAMES,
  AUTO_LOG_MAX_QUEUED_BYTES,
  AUTO_LOG_MAX_QUEUED_ENTRIES,
  AUTO_LOG_TERMINAL_TIMEOUT_MS,
  AutoLogBridge,
  AutoLogShutdownError,
  autoLogFormatForDisplayMode,
  createAutoLogBridge,
  useAutoLog,
  type AutoLogBridgeOptions,
  type AutoLogFailureReason,
  type AutoLogSessionClient,
  type AutoLogShutdownFailureStage,
  type UseAutoLogDeps,
} from './automation-bridge';
