use ts_rs::{Config, TS};

use crate::*;

const HEADER: &str =
    "// @generated by bbcom-contracts via ts-rs 12.0.1.\n// Do not edit this file by hand.\n\n";

/// Render every declaration in a frozen order into one deterministic module.
pub fn render_typescript() -> String {
    let config = Config::default();
    let mut output = String::with_capacity(32 * 1024);
    output.push_str(HEADER);

    macro_rules! declaration {
        ($type:ty) => {
            append_declaration::<$type>(&mut output, &config)
        };
    }

    declaration!(AppErrorCode);
    declaration!(IpcError);
    declaration!(Direction);
    declaration!(DataFramePayload);
    declaration!(ChecksumType);
    declaration!(ChecksumRequest);
    declaration!(ChecksumResponse);
    declaration!(ExportFormat);
    declaration!(ExportSource);
    declaration!(BeginExportRequest);
    declaration!(AppendExportBatchRequest);
    declaration!(ExportSessionRequest);
    declaration!(BeginExportResponse);
    declaration!(ExportAppendStats);
    declaration!(ExportFinishStats);
    declaration!(AutoLogFormat);
    declaration!(BeginAutoLogRequest);
    declaration!(BeginAutoLogResponse);
    declaration!(AppendAutoLogBatchRequest);
    declaration!(AutoLogAppendStats);
    declaration!(AutoLogSessionRequest);
    declaration!(SaveTargetPurpose);
    declaration!(RequestSaveTargetRequest);
    declaration!(SaveTargetGrantResponse);
    declaration!(RevokeFileGrantRequest);
    declaration!(AiRequestKind);
    declaration!(RunAiRequest);
    declaration!(AiRisk);
    declaration!(TerminalAiResponse);
    declaration!(LogAiResponse);
    declaration!(AiRequestResult);
    declaration!(CancelAiRequest);
    declaration!(AiWindowState);
    declaration!(ResizeAiWindowRequest);
    declaration!(AiKeyDurability);
    declaration!(AiKeyStatus);
    declaration!(SetAiApiKeyRequest);
    declaration!(MigrateAiApiKeyRequest);
    declaration!(StateOrigin);
    declaration!(StateEnvelope<()>);
    declaration!(OperationStatus);
    declaration!(OperationKind);
    declaration!(OperationRecord);
    declaration!(CancelOperationRequest);
    declaration!(PluginPermission);
    declaration!(PluginLifecycleStatus);
    declaration!(PluginStatusReason);
    declaration!(PluginUnavailableCapability);
    declaration!(PluginCatalogItem);
    declaration!(PluginSourceKind);
    declaration!(PluginSourceHealth);
    declaration!(PluginSourceView);
    declaration!(RuntimeInstanceKey);
    declaration!(InstalledPluginView);
    declaration!(PluginSerialProposal);
    declaration!(PluginPanelFieldKind);
    declaration!(PluginPanelField);
    declaration!(PluginDeclarativePanel);
    declaration!(PluginPanelEvent);
    declaration!(PluginCenterData);
    declaration!(PluginFailureCode);
    declaration!(PluginFailure);
    declaration!(PluginCommandResponse);
    declaration!(PluginSnapshotRequest);
    declaration!(InstallPluginRequest);
    declaration!(InstallLocalPluginRequest);
    declaration!(PluginLocalSourceKind);
    declaration!(RequestPluginLocalSourceGrantRequest);
    declaration!(PluginLocalSourceGrantResponse);
    declaration!(UninstallPluginRequest);
    declaration!(SetPluginEnabledRequest);
    declaration!(AddPluginSourceRequest);
    declaration!(UpdatePluginSourceRequest);
    declaration!(RemovePluginSourceRequest);
    declaration!(RefreshPluginSourceRequest);
    declaration!(SetPluginWatchEnabledRequest);
    declaration!(PluginSerialProposalDecision);
    declaration!(ResolvePluginSerialProposalRequest);
    declaration!(PluginSerialAction);
    declaration!(PluginSerialActionResultRequest);
    declaration!(PluginSessionQuery);
    declaration!(PluginSessionQueryKind);
    declaration!(PluginSessionQueryResult);
    declaration!(PluginSessionSummary);
    declaration!(PluginCapturedFrame);
    declaration!(EmitPluginPanelEventRequest);
    declaration!(CancelPluginOperationRequest);
    declaration!(SerialSendOutcome);
    declaration!(SerialSendResult);
    declaration!(SerialDrainCompletion);
    declaration!(SerialDrainRequest);
    declaration!(SerialDrainResponse);
    declaration!(PortLeaseState);
    declaration!(PortLeaseOwner);
    declaration!(AcquirePortLeaseRequest);
    declaration!(PortLeaseGrant);
    declaration!(ReleasePortLeaseRequest);
    declaration!(PortLeaseConflict);
    declaration!(ShutdownState);
    declaration!(ShutdownDecisionState);
    declaration!(ShutdownParticipantStatus);
    declaration!(ShutdownParticipantMessageKey);
    declaration!(ShutdownParticipantReport);
    declaration!(ShutdownReport);
    declaration!(ShutdownCloseRequest);
    declaration!(ShutdownDrainResult);
    declaration!(ShutdownConfirmation);
    declaration!(ShutdownCancellation);
    declaration!(WorkspaceSaveHealth);
    declaration!(WorkspaceSummary);
    declaration!(WorkspaceCatalogRequest);
    declaration!(WorkspaceCatalogResponse);
    declaration!(CreateWorkspaceCommandRequest);
    declaration!(CreateWorkspaceCommandResponse);
    declaration!(OpenWorkspaceRequest);
    declaration!(OpenWorkspaceResponse);
    declaration!(DeleteWorkspaceRequest);
    declaration!(DeleteWorkspaceResponse);
    declaration!(HydrateWorkspaceSessionsRequest);
    declaration!(WorkspaceSessionSnapshot);
    declaration!(HydrateWorkspaceSessionsResponse);
    declaration!(HydrateWorkspaceFramesRequest);
    declaration!(WorkspaceHydratedFrame);
    declaration!(HydrateWorkspaceFramesResponse);
    declaration!(WorkspaceDocumentHeader);
    declaration!(WorkspaceMutationKind);
    declaration!(WorkspaceMetadataPayload);
    declaration!(WorkspacePortHint);
    declaration!(WorkspaceSessionKind);
    declaration!(WorkspaceSessionUpsertPayload);
    declaration!(WorkspaceFramePayload);
    declaration!(WorkspaceAppendFramesPayload);
    declaration!(WorkspaceReplaceCapturePayload);
    declaration!(WorkspaceTrimCapturePayload);
    declaration!(WorkspaceFeatureKind);
    declaration!(WorkspaceFeatureStatePayload);
    declaration!(WorkspaceSendHistoryEntry);
    declaration!(WorkspaceQuickCommand);
    declaration!(WorkspaceMacroStep);
    declaration!(WorkspaceMacro);
    declaration!(WorkspaceConfigRow);
    declaration!(WorkspaceSessionCollectionsPayload);
    declaration!(HydrateWorkspaceCollectionsRequest);
    declaration!(HydrateWorkspaceCollectionsResponse);
    declaration!(WorkspaceAiRole);
    declaration!(WorkspaceAiMessage);
    declaration!(WorkspaceAiMessagesPayload);
    declaration!(HydrateWorkspaceAiMessagesRequest);
    declaration!(HydrateWorkspaceAiMessagesResponse);
    declaration!(WorkspaceWaveformSample);
    declaration!(WorkspaceWaveformChannel);
    declaration!(WorkspaceWaveformChannelsPayload);
    declaration!(WorkspaceWaveformSamplesPayload);
    declaration!(HydrateWorkspaceWaveformRequest);
    declaration!(HydrateWorkspaceWaveformResponse);
    declaration!(WorkspaceMutation);
    declaration!(ApplyWorkspaceBatchRequest);
    declaration!(ApplyWorkspaceBatchResponse);
    declaration!(FlushWorkspaceRequest);
    declaration!(FlushWorkspaceResponse);
    declaration!(ProjectEncryptionMode);
    declaration!(ProjectEncryptionOptions);
    declaration!(RequestProjectSourceGrantRequest);
    declaration!(ProjectSourceGrantResponse);
    declaration!(RequestProjectTargetGrantRequest);
    declaration!(ProjectTargetGrantResponse);
    declaration!(ImportProjectRequest);
    declaration!(ImportProjectResponse);
    declaration!(ExportProjectRequest);
    declaration!(ExportProjectResponse);
    declaration!(CancelWorkspaceOperationRequest);
    declaration!(CancelWorkspaceOperationResponse);
    declaration!(LegacyBackupFormat);
    declaration!(LegacyBackupSourceVersion);
    declaration!(LegacyBackupContent);
    declaration!(BeginLegacyBackupRequest);
    declaration!(BeginLegacyBackupResponse);
    declaration!(VerifyLegacyBackupRequest);
    declaration!(VerifyLegacyBackupResponse);
    declaration!(LegacyResetJournalPhase);
    declaration!(LegacyResetJournal);
    declaration!(GetLegacyResetJournalRequest);
    declaration!(GetLegacyResetJournalResponse);
    declaration!(BeginLegacyDiscardRequest);
    declaration!(BeginLegacyDiscardResponse);
    declaration!(PrepareLegacyResetRequest);
    declaration!(PrepareLegacyResetResponse);
    declaration!(CompleteLegacyResetRequest);
    declaration!(CompleteLegacyResetResponse);

    output.push_str("/** Stable alias used by existing frontend error handling. */\n");
    output.push_str("export type AppError = IpcError;\n\n");
    output.push_str("/** Compatibility aliases for the current frontend IPC wrappers. */\n");
    output.push_str("export type ExportFramePayload = DataFramePayload;\n");
    output.push_str("export type SaveTargetGrant = SaveTargetGrantResponse;\n\n");
    append_limits(&mut output);
    // ts-rs 12 wraps long member lists leaving a trailing space before the
    // newline. Strip per-line trailing whitespace so the rendered module is
    // lint-clean and matches the committed generated file byte for byte.
    let mut rendered = String::with_capacity(output.len());
    for line in output.lines() {
        rendered.push_str(line.trim_end());
        rendered.push('\n');
    }
    rendered
}

fn append_declaration<T: TS>(output: &mut String, config: &Config) {
    let declaration = T::decl(config);
    output.push_str("export ");
    output.push_str(declaration.trim());
    if !declaration.trim_end().ends_with(';') {
        output.push(';');
    }
    output.push_str("\n\n");
}

fn append_limits(output: &mut String) {
    output.push_str("/** Numeric limits enforced by the Rust command boundary. */\n");
    output.push_str("export const IPC_LIMITS = {\n");
    macro_rules! limit {
        ($name:ident) => {
            output.push_str(concat!("  ", stringify!($name), ": "));
            output.push_str(&$name.to_string());
            output.push_str(",\n");
        };
    }
    limit!(MAX_CHECKSUM_DATA_BYTES);
    limit!(MAX_EXPORT_FRAMES);
    limit!(MAX_EXPORT_BYTES);
    limit!(MAX_EXPORT_FRAME_BYTES);
    limit!(MAX_EXPORT_BATCH_FRAMES);
    limit!(MAX_EXPORT_BATCH_BYTES);
    limit!(MAX_AUTO_LOG_BATCH_FRAMES);
    limit!(MAX_AUTO_LOG_BATCH_BYTES);
    limit!(MAX_AUTO_LOG_FRAME_ID_BYTES);
    limit!(MAX_AI_REQUEST_ID_BYTES);
    limit!(MAX_AI_PROMPT_BYTES);
    limit!(MAX_AI_CONTEXT_BYTES);
    limit!(MAX_AI_MODEL_BYTES);
    limit!(MAX_AI_SHELL_BYTES);
    limit!(MAX_AI_SESSION_META_BYTES);
    limit!(MAX_AI_CONTEXT_MODE_BYTES);
    limit!(MAX_AI_RESPONSE_BYTES);
    limit!(MAX_CONCURRENT_AI_REQUESTS);
    limit!(MAX_SERIAL_DRAIN_BYTES);
    limit!(MAX_SERIAL_PORT_PATH_BYTES);
    limit!(MAX_WORKSPACE_SESSIONS);
    limit!(MAX_WORKSPACE_FRAMES_PER_SESSION);
    limit!(MAX_WORKSPACE_FRAMES);
    limit!(MAX_WORKSPACE_FRAME_BYTES);
    limit!(MAX_WORKSPACE_CAPTURE_BYTES);
    limit!(MAX_WORKSPACE_DATABASE_BYTES);
    limit!(MAX_LEGACY_BACKUP_CONTENT_BYTES);
    limit!(MAX_WORKSPACE_MUTATIONS_PER_BATCH);
    limit!(MAX_WORKSPACE_FRAMES_PER_BATCH);
    limit!(MAX_WORKSPACE_BATCH_BYTES);
    limit!(MAX_WORKSPACE_AI_MESSAGES);
    limit!(MAX_WORKSPACE_AI_MESSAGE_BYTES);
    limit!(MAX_WORKSPACE_AI_BYTES);
    limit!(MAX_PLUGIN_STATE_BYTES);
    limit!(MAX_WORKSPACE_PLUGIN_STATE_BYTES);
    limit!(MAX_PLUGIN_CATALOG_ITEMS);
    limit!(MAX_INSTALLED_PLUGINS);
    limit!(MAX_PLUGIN_AUTHORIZATION_PERMISSIONS);
    limit!(MAX_PLUGIN_SERIAL_PROPOSALS);
    limit!(MAX_PLUGIN_PANELS);
    limit!(MAX_PLUGIN_PANEL_FIELDS);
    limit!(MAX_PLUGIN_PANEL_OPTIONS);
    limit!(MAX_PLUGIN_PANEL_TEXT_BYTES);
    limit!(MAX_PLUGIN_ID_BYTES);
    limit!(MAX_PLUGIN_VERSION_BYTES);
    limit!(MAX_PLUGIN_DISPLAY_NAME_BYTES);
    limit!(MAX_PLUGIN_DESCRIPTION_BYTES);
    limit!(MAX_PLUGIN_PANEL_TITLE_BYTES);
    limit!(MAX_PLUGIN_PANEL_FIELD_ID_BYTES);
    limit!(MAX_PLUGIN_PANEL_LABEL_BYTES);
    limit!(MAX_PLUGIN_PANEL_VALUE_BYTES);
    limit!(MAX_PLUGIN_PANEL_OPTION_BYTES);
    limit!(MAX_PLUGIN_HEX_PREVIEW_BYTES);
    output.push_str("} as const;\n\n");
    output.push_str("export const IPC_CONTRACT_SCHEMA_VERSION = ");
    output.push_str(&CONTRACT_SCHEMA_VERSION.to_string());
    output.push_str(" as const;\n");
}
